# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - Libraries/**
    - lib/**/*.g.dart
    - test/**/*.mocks.dart
    - lib/di/di_setup.config.dart
    - plugins/**

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_require_non_null_named_parameters: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_multiple_declarations_per_line: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    curly_braces_in_flow_control_structures: true
    eol_at_end_of_file: true
    no_duplicate_case_values: true
    one_member_abstracts: false
    only_throw_errors: true
    package_api_docs: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_void_to_null: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    unnecessary_await_in_return: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
    valid_regexps: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
