name: cifraclub
description: Aprenda a tocar um instrumento com cifras e videoaulas gratuitas
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  appcheck: ^1.0.6
  async: ^2.10.0
  cached_network_image: ^3.2.3
  clock: ^1.1.1
  copy_with_extension: ^5.0.1
  cosmos:
    git:
      url: "git@github.com:CifraClub/CosmosMobile.git"
      ref: "ea47f93bf69ca653b416504b798380f8564e5bf2"
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  device_info_plus: ^8.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  file: ^6.1.4
  firebase_analytics: ^10.0.8
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^3.0.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_color_models: ^1.3.3+2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  in_app_purchase: ^3.1.5
  in_app_purchase_android: ^0.2.4+3
  in_app_purchase_storekit: ^0.3.6+2
  injectable: ^1.5.4
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.7.0
  lehttp_overrides: ^1.0.2
  logging: ^1.1.0
  mutex: ^3.0.1
  nav:
    git:
      url: "git@github.com:CifraClub/flutter_nav.git"
      ref: "1.0.0"
  network_image_mock: ^2.1.1
  ntp: ^2.0.0
  path_provider: ^2.0.12
  quiver: ^3.2.1
  rxdart: ^0.27.7
  scroll_loop_auto_scroll: ^0.0.5
  typed_result: ^1.0.1
  url_launcher: ^6.1.10

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.1
  dlcov: ^4.2.1
  faker: ^2.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  images_files_checker: ^0.0.2
  injectable_generator:
  isar_generator: ^3.0.5
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  pull_request_coverage: ^0.0.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900

