name: cifraclub
description: Aprenda a tocar um instrumento com cifras e videoaulas gratuitas

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  clock: ^1.1.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter

  get_it: ^7.2.0
  injectable: ^1.5.4
  intl: ^0.17.0
  ntp: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  injectable_generator:
  mocktail: ^0.3.0

flutter:
  generate: true

  uses-material-design: true