name: cifraclub
description: Aprenda a tocar um instrumento com cifras e videoaulas gratuitas
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  clock: ^1.1.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_analytics: ^10.0.8
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^3.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.4
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  mutex: ^3.0.1
  ntp: ^2.0.0
  rxdart: ^0.27.7
  typed_result: ^0.0.3

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner:
  dlcov: ^4.2.1
  faker: ^2.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  images_files_checker: ^0.0.2
  injectable_generator:
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  pull_request_coverage: ^0.0.5

flutter:
  generate: true

  uses-material-design: true
